### ISSUE TITLE
installer still permission issues on linux

### ISSUE THREAD

**Issue by tetchel** [tetchel/Shexter#13]
tim@wintergreen ~ $ shexter hello
Traceback (most recent call last):
  File "/opt/shexter/shexter.py", line 10, in <module>
    from appdirs import user_config_dir
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 766, in get_code
  File "<frozen importlib._bootstrap_external>", line 818, in get_data
PermissionError: [Errno 13] Permission denied: '/opt/shexter/appdirs.py'

**Comment by allan2** [comment]
I did not experience this. My appdirs.py permission is 751. What is yours?

**Comment by tetchel** [comment]
I can't reproduce this, will have to see if it returns
