### ISSUE TITLE
ugly message when cancelling input

### ISSUE THREAD

**Issue by tetchel** [tetchel/Shexter#14]
[ /home/tim ] $ shexter send
You must specify a Contact Name for Send and Read and SetPref commands. Enter one now:
Enter a new contact name (CTRL + C to give up): ^C
Traceback (most recent call last):
  File "/opt/shexter/shexter.py", line 416, in <module>
    main(sys.argv[1:])
  File "/opt/shexter/shexter.py", line 402, in main
    command, request = build_request(args)
TypeError: 'NoneType' object is not iterable
[ /home/tim ] $

**Comment by tetchel** [comment]
trivial to fix this by catching and passing the exception
